2018-03-22 18:14:03.937 [error] <0.274.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.279.0> exit with reason normal in context child_terminated
2018-03-22 18:14:04.010 [info] <0.33.0> Application lager started on node 'server@NT-21'
2018-03-22 18:14:04.034 [info] <0.33.0> Application xmerl started on node 'server@NT-21'
2018-03-22 18:14:04.052 [info] <0.33.0> Application jsx started on node 'server@NT-21'
2018-03-22 18:14:04.122 [info] <0.33.0> Application ranch started on node 'server@NT-21'
2018-03-22 18:14:04.134 [info] <0.33.0> Application ranch_proxy_protocol started on node 'server@NT-21'
2018-03-22 18:14:04.145 [info] <0.33.0> Application recon started on node 'server@NT-21'
2018-03-22 18:14:04.145 [info] <0.33.0> Application rabbit_common started on node 'server@NT-21'
2018-03-22 18:14:04.166 [info] <0.33.0> Application amqp_client started on node 'server@NT-21'
2018-03-22 18:14:04.167 [info] <0.33.0> Application amqp started on node 'server@NT-21'
2018-03-22 18:14:04.187 [info] <0.33.0> Application poison started on node 'server@NT-21'
2018-03-22 18:14:04.228 [info] <0.33.0> Application earmark started on node 'server@NT-21'
2018-03-22 18:14:04.228 [info] <0.33.0> Application ex_doc started on node 'server@NT-21'
2018-03-22 18:14:04.228 [info] <0.33.0> Application battleships started on node 'server@NT-21'
2018-03-22 18:14:04.669 [info] <0.33.0> Application battleship_server started on node 'server@NT-21'
2018-03-22 18:16:04.660 [error] <0.376.0> gen_server <0.376.0> terminated with reason: {socket_error,timeout}
2018-03-22 18:16:04.661 [error] <0.372.0> gen_server <0.372.0> terminated with reason: {socket_error,timeout}
2018-03-22 18:16:04.661 [error] <0.376.0> CRASH REPORT Process <0.376.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 18:16:04.661 [error] <0.372.0> CRASH REPORT Process <0.372.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 18:16:04.661 [error] <0.370.0> Supervisor {<0.370.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.371.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.372.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 18:16:04.661 [error] <0.370.0> Supervisor {<0.370.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.371.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.372.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 18:16:04.661 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13231>, <0.372.0>, <0.374.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60141 -> 127.0.0.1:5672">>) at <0.376.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 18:16:04.661 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13231>, <0.372.0>, <0.374.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60141 -> 127.0.0.1:5672">>) at <0.376.0> exit with reason reached_max_restart_intensity in context shutdown
