2018-03-22 11:17:57.983 [error] <0.267.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.272.0> exit with reason normal in context child_terminated
2018-03-22 11:17:58.671 [error] <0.374.0> 'Elixir.BattleshipServer.Store' <0.374.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-_GO4I38En1-K1p_CkKPTTg">>}}
2018-03-22 11:18:39.132 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 11:18:39.821 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-CgzS8trlKNRRSPQZ5Ys0fg">>}}
2018-03-22 11:19:39.756 [error] <0.304.0> gen_server <0.304.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:19:39.772 [error] <0.300.0> gen_server <0.300.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:19:39.772 [error] <0.300.0> CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:19:39.772 [error] <0.304.0> CRASH REPORT Process <0.304.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:19:39.772 [error] <0.298.0> Supervisor {<0.298.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.299.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.300.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:19:39.772 [error] <0.298.0> Supervisor {<0.298.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.299.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.300.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:19:39.772 [error] <0.299.0> Supervisor {<0.299.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7527>, <0.300.0>, <0.302.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63686 -> 127.0.0.1:5672">>) at <0.304.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:19:39.772 [error] <0.299.0> Supervisor {<0.299.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7527>, <0.300.0>, <0.302.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63686 -> 127.0.0.1:5672">>) at <0.304.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:19:44.365 [error] <0.181.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.186.0> exit with reason normal in context child_terminated
2018-03-22 11:19:45.057 [error] <0.288.0> 'Elixir.BattleshipServer.Store' <0.288.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-D-HQa9HTq7h3XmWEmQwaKg">>}}
2018-03-22 11:20:21.385 [error] <0.181.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.186.0> exit with reason normal in context child_terminated
2018-03-22 11:20:22.279 [error] <0.288.0> 'Elixir.BattleshipServer.Store' <0.288.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-q5nVCebCB5-tWX82Pg_W0A">>}}
2018-03-22 11:20:25.476 [error] <0.306.0> ** Connection attempt from disallowed node 'cl1@NT-21' ** 
2018-03-22 11:20:46.936 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 11:20:47.828 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-0YoST14bWB-6DbpBzhTDfg">>}}
2018-03-22 11:21:20.746 [error] emulator Error in process <0.296.0> on node 'server@NT-21' with exit value:
{function_clause,[{lists,reverse,[{game_created,-576460752303423487,<<"Alex">>,<<"Manos">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 11:21:20.747 [error] <0.293.0>@lists:reverse:147 Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7474>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:63760 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason no function clause matching lists:reverse({game_created,-576460752303423487,<<"Alex">>,<<"Manos">>}) line 147 in context child_terminated
2018-03-22 11:21:20.747 [error] <0.293.0> Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7474>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:63760 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:21:47.749 [error] <0.304.0> gen_server <0.304.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:21:47.767 [error] <0.300.0> gen_server <0.300.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:21:47.767 [error] <0.304.0> CRASH REPORT Process <0.304.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:21:47.767 [error] <0.300.0> CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:21:47.767 [error] <0.299.0> Supervisor {<0.299.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7633>, <0.300.0>, <0.302.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63761 -> 127.0.0.1:5672">>) at <0.304.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:21:47.767 [error] <0.299.0> Supervisor {<0.299.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7633>, <0.300.0>, <0.302.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63761 -> 127.0.0.1:5672">>) at <0.304.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:21:47.767 [error] <0.298.0> Supervisor {<0.298.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.299.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.300.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:21:47.767 [error] <0.298.0> Supervisor {<0.298.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.299.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.300.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:22:47.685 [error] <0.290.0> gen_server <0.290.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:22:47.685 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:22:47.686 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7474>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63760 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:22:47.687 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7474>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63760 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:22:47.689 [error] <0.286.0> gen_server <0.286.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:22:47.689 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:22:47.690 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:22:47.690 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:23:01.965 [error] <0.283.0>@gen_server:call gen_server game_server terminated with reason: no such process or port in call to gen_server:call(<0.295.0>, {call,{'basic.publish',0,<<"game">>,<<"start_stop">>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 60000) in gen_server:call/3 line 214
2018-03-22 11:23:01.965 [error] <0.283.0>@gen_server:call CRASH REPORT Process game_server with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.295.0>, {call,{'basic.publish',0,<<"game">>,<<"start_stop">>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 60000) in gen_server:call/3 line 214
2018-03-22 11:23:01.965 [error] <0.280.0>@gen_server:call Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.Game.Server' started with 'Elixir.Game.Server':start_link([]) at <0.283.0> exit with reason no such process or port in call to gen_server:call(<0.295.0>, {call,{'basic.publish',0,<<"game">>,<<"start_stop">>,false,false},{amqp_msg,{'P_basic',undefined,...},...},...}, 60000) in context child_terminated
2018-03-22 11:24:01.996 [error] <0.331.0> gen_server <0.331.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:24:01.996 [error] <0.331.0> CRASH REPORT Process <0.331.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:24:01.997 [error] <0.327.0> gen_server <0.327.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:24:01.997 [error] <0.327.0> CRASH REPORT Process <0.327.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:24:01.997 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.326.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.327.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:24:01.997 [error] <0.325.0> Supervisor {<0.325.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.326.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.327.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:24:01.998 [error] <0.326.0> Supervisor {<0.326.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8348>, <0.327.0>, <0.329.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63822 -> 127.0.0.1:5672">>) at <0.331.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:24:01.998 [error] <0.326.0> Supervisor {<0.326.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.8348>, <0.327.0>, <0.329.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63822 -> 127.0.0.1:5672">>) at <0.331.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:28:28.937 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 11:28:29.637 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-Y1Ygeu3emrRRdCpY83dGQw">>}}
2018-03-22 11:28:50.711 [error] emulator Error in process <0.296.0> on node 'server@NT-21' with exit value:
{function_clause,[{lists,reverse,[{game_created,-576460752303423135,<<"Alex">>,<<"Manos">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 11:28:50.711 [error] <0.293.0>@lists:reverse:147 Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7422>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:49479 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason no function clause matching lists:reverse({game_created,-576460752303423135,<<"Alex">>,<<"Manos">>}) line 147 in context child_terminated
2018-03-22 11:28:50.711 [error] <0.293.0> Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7422>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:49479 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:30:29.531 [error] <0.290.0> gen_server <0.290.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:30:29.531 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:30:29.552 [error] <0.286.0> gen_server <0.286.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:30:29.552 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:30:29.553 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7422>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49479 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:30:29.553 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7422>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49479 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:30:29.553 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:30:29.553 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:31:17.156 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 11:31:17.895 [error] <0.302.0> 'Elixir.BattleshipServer.Store' <0.302.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-jtNYm92fjnLwi1TLSkahvw">>}}
2018-03-22 11:32:38.193 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 11:32:38.868 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-qjj_-INJt4HMjICzYEqtdg">>}}
2018-03-22 11:32:44.014 [error] emulator Error in process <0.296.0> on node 'server@NT-21' with exit value:
{function_clause,[{lists,reverse,[{game_created,-576460752303422718,<<"Manos">>,<<"Alex">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 11:32:44.014 [error] <0.293.0>@lists:reverse:147 Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7475>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:49579 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason no function clause matching lists:reverse({game_created,-576460752303422718,<<"Manos">>,<<"Alex">>}) line 147 in context child_terminated
2018-03-22 11:32:44.015 [error] <0.293.0> Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7475>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:49579 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:34:38.792 [error] <0.290.0> gen_server <0.290.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:34:38.792 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:34:38.844 [error] <0.286.0> gen_server <0.286.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:34:38.844 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:34:38.844 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7475>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49579 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:34:38.844 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7475>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49579 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:34:38.844 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:34:38.844 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:41:12.815 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 11:41:13.547 [error] <0.302.0> 'Elixir.BattleshipServer.Store' <0.302.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-pLW4nbJjlfQMObgZKDpZpw">>}}
2018-03-22 11:41:31.687 [error] emulator Error in process <0.301.0> on node 'server@NT-21' with exit value:
{function_clause,[{lists,reverse,[{-576460752303423068,<<"Alex">>,<<"Manos">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 11:41:31.687 [error] <0.298.0>@lists:reverse:147 Supervisor {<0.298.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7529>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.300.0>, {<<"client 127.0.0.1:49741 -> 127.0.0.1:5672">>,1}) at <0.301.0> exit with reason no function clause matching lists:reverse({-576460752303423068,<<"Alex">>,<<"Manos">>}) line 147 in context child_terminated
2018-03-22 11:41:31.688 [error] <0.298.0> Supervisor {<0.298.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7529>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.300.0>, {<<"client 127.0.0.1:49741 -> 127.0.0.1:5672">>,1}) at <0.301.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:43:13.443 [error] <0.295.0> gen_server <0.295.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:43:13.443 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:43:13.470 [error] <0.291.0> gen_server <0.291.0> terminated with reason: {socket_error,timeout}
2018-03-22 11:43:13.470 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7529>, <0.291.0>, <0.293.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49741 -> 127.0.0.1:5672">>) at <0.295.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:43:13.470 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 11:43:13.470 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7529>, <0.291.0>, <0.293.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:49741 -> 127.0.0.1:5672">>) at <0.295.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:43:13.470 [error] <0.289.0> Supervisor {<0.289.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.290.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.291.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 11:43:13.470 [error] <0.289.0> Supervisor {<0.289.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.290.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.291.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 11:59:11.131 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 11:59:11.702 [error] <0.283.0> CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'direct' but current is 'fanout'">>}},{gen_server,call,[<0.295.0>,{call,{'exchange.declare',0,<<"game">>,<<"direct">>,false,false,false,false,false,[]},none,<0.283.0>},60000]}} in gen_server:call/3 line 214
2018-03-22 11:59:11.702 [error] <0.280.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.Game.Server' started with 'Elixir.Game.Server':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'direct' but current is 'fanout'">>}},{gen_server,call,[<0.295.0>,{call,{'exchange.declare',0,<<"game">>,<<"direct">>,false,false,false,false,false,[]},none,<0.283.0>},60000]}} in context start_error
2018-03-22 11:59:11.702 [error] <0.266.0> Supervisor 'Elixir.BattleshipServer.Supervisor' had child 'Elixir.Server.Supervisor' started with 'Elixir.Server.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.Game.Server',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'direct' but current is 'fanout'">>}},{gen_server,call,[<0.295.0>,{call,{'exchange.declare',0,<<"game">>,<<"direct">>,false,false,false,false,false,[]},none,<0.283.0>},60000]}}}} in context start_error
2018-03-22 11:59:11.703 [error] <0.264.0> CRASH REPORT Process <0.264.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Server.Supervisor',{shutdown,{failed_to_start_child,'Elixir.Game.Server',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'direct' but current is 'fanout'">>}},{gen_server,call,[<0.295.0>,{call,{'exchange.declare',0,<<"game">>,<<"direct">>,false,false,false,false,false,[]},none,<0.283.0>},60000]}}}}}},{'Elixir.BattleshipServer.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-03-22 12:02:00.662 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:02:01.375 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-75-R6djGpEiQtJNMbpgIzg">>}}
2018-03-22 12:03:17.188 [error] <0.181.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.186.0> exit with reason normal in context child_terminated
2018-03-22 12:03:17.905 [error] <0.288.0> 'Elixir.BattleshipServer.Store' <0.288.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-Zzv4cvc82-BuLvurEcawZA">>}}
2018-03-22 12:05:17.776 [error] <0.281.0> gen_server <0.281.0> terminated with reason: {socket_error,timeout}
2018-03-22 12:05:17.799 [error] <0.277.0> gen_server <0.277.0> terminated with reason: {socket_error,timeout}
2018-03-22 12:05:17.799 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 12:05:17.799 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 12:05:17.799 [error] <0.275.0> Supervisor {<0.275.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.276.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.277.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 12:05:17.799 [error] <0.276.0> Supervisor {<0.276.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6673>, <0.277.0>, <0.279.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50131 -> 127.0.0.1:5672">>) at <0.281.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 12:05:17.800 [error] <0.275.0> Supervisor {<0.275.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.276.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.277.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:05:17.800 [error] <0.276.0> Supervisor {<0.276.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6673>, <0.277.0>, <0.279.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50131 -> 127.0.0.1:5672">>) at <0.281.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:07:27.193 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:07:27.886 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-x5aIc_nSFMlOeBWpc2tPkA">>}}
2018-03-22 12:08:34.796 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:08:35.460 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-BLKY63157iqkVyZ5YmB0YQ">>}}
2018-03-22 12:10:21.622 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:10:22.326 [error] <0.297.0>@Elixir.BattleshipServer.Store:handle_info:21 gen_server <0.297.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-xpvTBIR4fRSxqvpkpjqlHg">>}}, nil) line 21
2018-03-22 12:10:22.326 [error] <0.297.0>@Elixir.BattleshipServer.Store:handle_info:21 CRASH REPORT Process <0.297.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-xpvTBIR4fRSxqvpkpjqlHg">>}}, nil) line 21
2018-03-22 12:10:22.327 [error] <0.280.0>@Elixir.BattleshipServer.Store:handle_info:21 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.297.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-xpvTBIR4fRSxqvpkpjqlHg">>}}, nil) line 21 in context child_terminated
2018-03-22 12:10:22.327 [error] <0.299.0>@Elixir.BattleshipServer.Store:handle_info:21 gen_server <0.299.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-rxkL33RoHsuxFyewo_AE5w">>}}, nil) line 21
2018-03-22 12:10:22.327 [error] <0.299.0>@Elixir.BattleshipServer.Store:handle_info:21 CRASH REPORT Process <0.299.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-rxkL33RoHsuxFyewo_AE5w">>}}, nil) line 21
2018-03-22 12:10:22.327 [error] <0.280.0>@Elixir.BattleshipServer.Store:handle_info:21 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.299.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-rxkL33RoHsuxFyewo_AE5w">>}}, nil) line 21 in context child_terminated
2018-03-22 12:10:22.327 [error] <0.302.0>@Elixir.BattleshipServer.Store:handle_info:21 gen_server <0.302.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-WoQ4bi8068oCz9QJUX830g">>}}, nil) line 21
2018-03-22 12:10:22.327 [error] <0.302.0>@Elixir.BattleshipServer.Store:handle_info:21 CRASH REPORT Process <0.302.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-WoQ4bi8068oCz9QJUX830g">>}}, nil) line 21
2018-03-22 12:10:22.328 [error] <0.280.0>@Elixir.BattleshipServer.Store:handle_info:21 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.302.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-WoQ4bi8068oCz9QJUX830g">>}}, nil) line 21 in context child_terminated
2018-03-22 12:10:22.328 [error] <0.304.0>@Elixir.BattleshipServer.Store:handle_info:21 gen_server <0.304.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-f--6YBo2r7WioIZ4ctDyEw">>}}, nil) line 21
2018-03-22 12:10:22.328 [error] <0.304.0>@Elixir.BattleshipServer.Store:handle_info:21 CRASH REPORT Process <0.304.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-f--6YBo2r7WioIZ4ctDyEw">>}}, nil) line 21
2018-03-22 12:10:22.328 [error] <0.280.0>@Elixir.BattleshipServer.Store:handle_info:21 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.304.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-f--6YBo2r7WioIZ4ctDyEw">>}}, nil) line 21 in context child_terminated
2018-03-22 12:10:22.328 [error] <0.280.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.304.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:10:22.328 [error] <0.266.0> Supervisor 'Elixir.BattleshipServer.Supervisor' had child 'Elixir.Server.Supervisor' started with 'Elixir.Server.Supervisor':start_link([]) at <0.280.0> exit with reason shutdown in context child_terminated
2018-03-22 12:10:22.329 [error] <0.322.0>@Elixir.BattleshipServer.Store:handle_info:21 gen_server <0.322.0> terminated with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-rdo6oDuno4x5gTpIRmRMAg">>}}, nil) line 21
2018-03-22 12:10:22.329 [error] <0.322.0>@Elixir.BattleshipServer.Store:handle_info:21 CRASH REPORT Process <0.322.0> with 0 neighbours crashed with reason: no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-rdo6oDuno4x5gTpIRmRMAg">>}}, nil) line 21
2018-03-22 12:10:22.329 [error] <0.306.0>@Elixir.BattleshipServer.Store:handle_info:21 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.322.0> exit with reason no function clause matching 'Elixir.BattleshipServer.Store':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-rdo6oDuno4x5gTpIRmRMAg">>}}, nil) line 21 in context child_terminated
2018-03-22 12:16:40.975 [error] <0.267.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.272.0> exit with reason normal in context child_terminated
2018-03-22 12:16:41.543 [error] emulator Error in process <0.375.0> on node 'server@NT-21' with exit value:
{badarg,[{erlang,monitor,[process,<<"store">>],[]},{'Elixir.AMQP.Basic','-consume/4-fun-0-',2,[{file,"lib/amqp/basic.ex"},{line,255}]}]}
2018-03-22 12:17:20.092 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:17:20.884 [error] emulator Error in process <0.298.0> on node 'server@NT-21' with exit value:
{badarg,[{erlang,send,[store,{basic_consume_ok,#{consumer_tag => <<"amq.ctag-Q4jSamy6ZUU-l7IiFNkRvQ">>}}],[]},{'Elixir.AMQP.Basic',do_start_consumer,2,[{file,"lib/amqp/basic.ex"},{line,269}]}]}
2018-03-22 12:17:43.338 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:17:44.275 [error] emulator Error in process <0.298.0> on node 'server@NT-21' with exit value:
{badarg,[{erlang,monitor,[process,<<>>],[]},{'Elixir.AMQP.Basic','-consume/4-fun-0-',2,[{file,"lib/amqp/basic.ex"},{line,255}]}]}
2018-03-22 12:19:44.093 [error] <0.290.0> gen_server <0.290.0> terminated with reason: {socket_error,timeout}
2018-03-22 12:19:44.124 [error] <0.286.0> gen_server <0.286.0> terminated with reason: {socket_error,timeout}
2018-03-22 12:19:44.124 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 12:19:44.125 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7422>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50358 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 12:19:44.125 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 12:19:44.125 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7422>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50358 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:19:44.125 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 12:19:44.125 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:21:18.290 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:21:18.964 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-OnxpZkSWhZs__zPbS_zjpg">>}}
2018-03-22 12:22:22.495 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:22:23.147 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-rpMuGt0S-jwqSGco32tqMA">>}}
2018-03-22 12:22:44.993 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 12:22:45.711 [error] <0.297.0> 'Elixir.BattleshipServer.Store' <0.297.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-u7srqhwyxQ78wZCVHWWe2A">>}}
2018-03-22 12:23:33.319 [error] emulator Error in process <0.296.0> on node 'server@NT-21' with exit value:
{function_clause,[{lists,reverse,[{-576460752303423481,<<"Alex">>,<<"Manos">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 12:23:33.319 [error] <0.293.0>@lists:reverse:147 Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7424>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:50484 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason no function clause matching lists:reverse({-576460752303423481,<<"Alex">>,<<"Manos">>}) line 147 in context child_terminated
2018-03-22 12:23:33.319 [error] <0.293.0> Supervisor {<0.293.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7424>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.295.0>, {<<"client 127.0.0.1:50484 -> 127.0.0.1:5672">>,1}) at <0.296.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:24:45.613 [error] <0.290.0> gen_server <0.290.0> terminated with reason: {socket_error,timeout}
2018-03-22 12:24:45.614 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 12:24:45.614 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7424>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50484 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 12:24:45.656 [error] <0.286.0> gen_server <0.286.0> terminated with reason: {socket_error,timeout}
2018-03-22 12:24:45.656 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7424>, <0.286.0>, <0.288.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:50484 -> 127.0.0.1:5672">>) at <0.290.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:24:45.656 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 12:24:45.656 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 12:24:45.656 [error] <0.284.0> Supervisor {<0.284.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.285.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.286.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 12:58:51.680 [error] <0.181.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.186.0> exit with reason normal in context child_terminated
2018-03-22 12:58:52.519 [error] <0.288.0> 'Elixir.BattleshipServer.Store' <0.288.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-om4s73A2h4fcnxjDzbmsFw">>}}
2018-03-22 13:00:52.402 [error] <0.281.0> gen_server <0.281.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:00:52.402 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:00:52.429 [error] <0.277.0> gen_server <0.277.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:00:52.429 [error] <0.277.0> CRASH REPORT Process <0.277.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:00:52.429 [error] <0.276.0> Supervisor {<0.276.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6700>, <0.277.0>, <0.279.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59982 -> 127.0.0.1:5672">>) at <0.281.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:00:52.429 [error] <0.275.0> Supervisor {<0.275.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.276.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.277.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:00:52.429 [error] <0.276.0> Supervisor {<0.276.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.6700>, <0.277.0>, <0.279.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59982 -> 127.0.0.1:5672">>) at <0.281.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:00:52.429 [error] <0.275.0> Supervisor {<0.275.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.276.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.277.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:02:34.988 [error] <0.181.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.186.0> exit with reason normal in context child_terminated
2018-03-22 13:02:36.045 [error] <0.288.0> 'Elixir.BattleshipServer.Store' <0.288.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-4ymmHLtwXAyP-3yYarWUMw">>}}
2018-03-22 13:02:51.950 [error] emulator Error in process <0.287.0> on node 'server@NT-21' with exit value:
{function_clause,[{lists,reverse,[{-576460752303423482,<<"Alex">>,<<"Manos">>}],[{file,"lists.erl"},{line,147}]},{rabbit_binary_generator,build_content_frames,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,81}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 13:02:51.950 [error] <0.284.0>@lists:reverse:147 Supervisor {<0.284.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6672>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.286.0>, {<<"client 127.0.0.1:60032 -> 127.0.0.1:5672">>,1}) at <0.287.0> exit with reason no function clause matching lists:reverse({-576460752303423482,<<"Alex">>,<<"Manos">>}) line 147 in context child_terminated
2018-03-22 13:02:51.950 [error] <0.284.0> Supervisor {<0.284.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.6672>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.286.0>, {<<"client 127.0.0.1:60032 -> 127.0.0.1:5672">>,1}) at <0.287.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:03:46.612 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 13:03:47.337 [error] <0.302.0> 'Elixir.BattleshipServer.Store' <0.302.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-62cAIOL9ctI6HcRREsq8XQ">>}}
2018-03-22 13:03:53.131 [error] emulator Error in process <0.301.0> on node 'server@NT-21' with exit value:
{badarg,[{erlang,size,[-576460752303423452],[]},{rabbit_binary_generator,build_content_frames,7,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,95}]},{rabbit_binary_generator,build_simple_content_frames,4,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_binary_generator.erl"},{line,70}]},{rabbit_writer,assemble_frames,5,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,311}]},{rabbit_writer,internal_send_command_async,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,341}]},{rabbit_writer,handle_message,3,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,209}]},{rabbit_writer,mainloop1,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,193}]},{rabbit_writer,mainloop,2,[{file,"/mnt/c/Users/a.alepis/Desktop/Battleship project/Battleship_Server/deps/rabbit_common/src/rabbit_writer.erl"},{line,184}]}]}
2018-03-22 13:03:53.131 [error] <0.298.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.298.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7555>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.300.0>, {<<"client 127.0.0.1:60069 -> 127.0.0.1:5672">>,1}) at <0.301.0> exit with reason bad argument in call to erlang:size(-576460752303423452) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-03-22 13:03:53.131 [error] <0.298.0> Supervisor {<0.298.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.7555>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.300.0>, {<<"client 127.0.0.1:60069 -> 127.0.0.1:5672">>,1}) at <0.301.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:05:47.233 [error] <0.295.0> gen_server <0.295.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:05:47.233 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:05:47.266 [error] <0.291.0> gen_server <0.291.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:05:47.266 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7555>, <0.291.0>, <0.293.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60069 -> 127.0.0.1:5672">>) at <0.295.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:05:47.266 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7555>, <0.291.0>, <0.293.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60069 -> 127.0.0.1:5672">>) at <0.295.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:05:47.267 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:05:47.267 [error] <0.289.0> Supervisor {<0.289.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.290.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.291.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:05:47.267 [error] <0.289.0> Supervisor {<0.289.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.290.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.291.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:25:39.777 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 13:25:40.535 [error] <0.302.0> 'Elixir.BattleshipServer.Store' <0.302.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-NaV4LfarQsVNFjN3R1RU_A">>}}
2018-03-22 13:26:40.464 [error] <0.309.0> gen_server <0.309.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:26:40.493 [error] <0.305.0> gen_server <0.305.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:26:40.493 [error] <0.305.0> CRASH REPORT Process <0.305.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:26:40.493 [error] <0.309.0> CRASH REPORT Process <0.309.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:26:40.493 [error] <0.304.0> Supervisor {<0.304.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7715>, <0.305.0>, <0.307.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60323 -> 127.0.0.1:5672">>) at <0.309.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:26:40.493 [error] <0.304.0> Supervisor {<0.304.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7715>, <0.305.0>, <0.307.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60323 -> 127.0.0.1:5672">>) at <0.309.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:26:40.493 [error] <0.303.0> Supervisor {<0.303.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.304.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.305.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:26:40.493 [error] <0.303.0> Supervisor {<0.303.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.304.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.305.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:29:35.086 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 13:29:35.787 [error] <0.284.0> 'Elixir.BattleshipServer.Store' <0.284.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-9MJAy1ibjPidUhAx0RFOwQ">>}}
2018-03-22 13:30:06.109 [error] <0.323.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(-576460752303421881) in rabbit_binary_generator:build_content_frames/7 line 95
2018-03-22 13:30:06.109 [error] <0.320.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.320.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8172>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.322.0>, {<<"client 127.0.0.1:59846 -> 127.0.0.1:5672">>,1}) at <0.323.0> exit with reason bad argument in call to erlang:size(-576460752303421881) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-03-22 13:30:06.109 [error] <0.320.0> Supervisor {<0.320.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8172>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.322.0>, {<<"client 127.0.0.1:59846 -> 127.0.0.1:5672">>,1}) at <0.323.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:31:31.121 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 13:31:32.169 [error] <0.289.0> 'Elixir.BattleshipServer.Store' <0.289.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-0XlRAK-DBQvWMNlQ4Cdxng">>}}
2018-03-22 13:33:32.031 [error] <0.296.0> gen_server <0.296.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:33:32.059 [error] <0.292.0> gen_server <0.292.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:33:32.059 [error] <0.296.0> CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:33:32.059 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:33:32.059 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.291.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.292.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:33:32.059 [error] <0.291.0> Supervisor {<0.291.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7529>, <0.292.0>, <0.294.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59884 -> 127.0.0.1:5672">>) at <0.296.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:33:32.059 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.291.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:33:32.059 [error] <0.291.0> Supervisor {<0.291.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7529>, <0.292.0>, <0.294.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59884 -> 127.0.0.1:5672">>) at <0.296.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:34:20.432 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 13:34:21.249 [error] <0.289.0> 'Elixir.BattleshipServer.Store' <0.289.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-mK-9VDrDNhMKaKVD6GWByg">>}}
2018-03-22 13:35:37.381 [error] <0.190.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.195.0> exit with reason normal in context child_terminated
2018-03-22 13:35:38.081 [error] <0.284.0> 'Elixir.BattleshipServer.Store' <0.284.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-V2-6Vr2WZZxpjS5tmmviIQ">>}}
2018-03-22 13:35:44.857 [error] <0.323.0>@rabbit_binary_generator:build_content_frames:95 CRASH REPORT Process <0.323.0> with 0 neighbours crashed with reason: bad argument in call to erlang:size(-576460752303423451) in rabbit_binary_generator:build_content_frames/7 line 95
2018-03-22 13:35:44.857 [error] <0.320.0>@rabbit_binary_generator:build_content_frames:95 Supervisor {<0.320.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8181>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.322.0>, {<<"client 127.0.0.1:59991 -> 127.0.0.1:5672">>,1}) at <0.323.0> exit with reason bad argument in call to erlang:size(-576460752303423451) in rabbit_binary_generator:build_content_frames/7 line 95 in context child_terminated
2018-03-22 13:35:44.858 [error] <0.320.0> Supervisor {<0.320.0>,amqp_channel_sup} had child writer started with rabbit_writer:start_link(#Port<0.8181>, 1, 131072, rabbit_framing_amqp_0_9_1, <0.322.0>, {<<"client 127.0.0.1:59991 -> 127.0.0.1:5672">>,1}) at <0.323.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:37:38.003 [error] <0.291.0> gen_server <0.291.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:37:38.003 [error] <0.291.0> CRASH REPORT Process <0.291.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:37:38.037 [error] <0.287.0> gen_server <0.287.0> terminated with reason: {socket_error,timeout}
2018-03-22 13:37:38.037 [error] <0.287.0> CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 13:37:38.038 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.286.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.287.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:37:38.038 [error] <0.286.0> Supervisor {<0.286.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7446>, <0.287.0>, <0.289.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59984 -> 127.0.0.1:5672">>) at <0.291.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 13:37:38.038 [error] <0.285.0> Supervisor {<0.285.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.286.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.287.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 13:37:38.038 [error] <0.286.0> Supervisor {<0.286.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7446>, <0.287.0>, <0.289.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:59984 -> 127.0.0.1:5672">>) at <0.291.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 14:45:46.643 [error] <0.195.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.200.0> exit with reason normal in context child_terminated
2018-03-22 14:45:47.422 [error] <0.289.0> 'Elixir.BattleshipServer.Store' <0.289.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-RmFykq4_D3y7vmu9CsU9wQ">>}}
2018-03-22 14:47:03.380 [error] <0.286.0> gen_server game_server terminated with reason: {'module could not be loaded',[{ok,games,[],[]},{'Elixir.Game.Server','is_unique?',2,[{file,"lib/battleship_server/game_server.ex"},{line,58}]},{'Elixir.Game.Server',join_player,3,[{file,"lib/battleship_server/game_server.ex"},{line,18}]},{'Elixir.Game.Server',handle_info,2,[{file,"lib/battleship_server/game_server.ex"},{line,52}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,...},...]}]}
2018-03-22 14:47:03.380 [error] <0.286.0>@ok:games CRASH REPORT Process game_server with 0 neighbours crashed with reason: call to undefined function ok:games()
2018-03-22 14:47:03.380 [error] <0.285.0>@ok:games Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.Game.Server' started with 'Elixir.Game.Server':start_link([]) at <0.286.0> exit with reason call to undefined function ok:games() in context child_terminated
2018-03-22 14:47:47.317 [error] <0.296.0> gen_server <0.296.0> terminated with reason: {socket_error,timeout}
2018-03-22 14:47:47.317 [error] <0.296.0> CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 14:47:47.352 [error] <0.292.0> gen_server <0.292.0> terminated with reason: {socket_error,timeout}
2018-03-22 14:47:47.353 [error] <0.292.0> CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 14:47:47.353 [error] <0.291.0> Supervisor {<0.291.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7557>, <0.292.0>, <0.294.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63795 -> 127.0.0.1:5672">>) at <0.296.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 14:47:47.353 [error] <0.291.0> Supervisor {<0.291.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7557>, <0.292.0>, <0.294.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63795 -> 127.0.0.1:5672">>) at <0.296.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 14:47:47.353 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.291.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.292.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 14:47:47.353 [error] <0.290.0> Supervisor {<0.290.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.291.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.292.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 14:47:53.507 [error] <0.181.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.186.0> exit with reason normal in context child_terminated
2018-03-22 14:47:54.201 [error] <0.275.0> 'Elixir.BattleshipServer.Store' <0.275.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-5VZkpKj5tSi4NUW9zP_UAA">>}}
2018-03-22 14:48:02.090 [error] <0.275.0>@Elixir.BattleshipServer.Store:wait_for_messages:33 gen_server <0.275.0> terminated with reason: no match of right hand value <<"ManosAlex-576460752303423135">> in 'Elixir.BattleshipServer.Store':wait_for_messages/1 line 33
2018-03-22 14:48:02.090 [error] <0.275.0>@Elixir.BattleshipServer.Store:wait_for_messages:33 CRASH REPORT Process <0.275.0> with 0 neighbours crashed with reason: no match of right hand value <<"ManosAlex-576460752303423135">> in 'Elixir.BattleshipServer.Store':wait_for_messages/1 line 33
2018-03-22 14:48:02.090 [error] <0.271.0>@Elixir.BattleshipServer.Store:wait_for_messages:33 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.275.0> exit with reason no match of right hand value <<"ManosAlex-576460752303423135">> in 'Elixir.BattleshipServer.Store':wait_for_messages/1 line 33 in context child_terminated
2018-03-22 14:48:02.090 [error] <0.315.0> 'Elixir.BattleshipServer.Store' <0.315.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-fsdciHseydeVVOcjqQmSJA">>}}
2018-03-22 14:49:02.103 [error] <0.322.0> gen_server <0.322.0> terminated with reason: {socket_error,timeout}
2018-03-22 14:49:02.103 [error] <0.322.0> CRASH REPORT Process <0.322.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 14:49:02.157 [error] <0.318.0> gen_server <0.318.0> terminated with reason: {socket_error,timeout}
2018-03-22 14:49:02.157 [error] <0.318.0> CRASH REPORT Process <0.318.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 14:49:02.157 [error] <0.317.0> Supervisor {<0.317.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7441>, <0.318.0>, <0.320.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63856 -> 127.0.0.1:5672">>) at <0.322.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 14:49:02.157 [error] <0.317.0> Supervisor {<0.317.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7441>, <0.318.0>, <0.320.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:63856 -> 127.0.0.1:5672">>) at <0.322.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 14:49:02.158 [error] <0.316.0> Supervisor {<0.316.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.317.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.318.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 14:49:02.158 [error] <0.316.0> Supervisor {<0.316.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.317.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.318.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 15:20:15.496 [error] <0.274.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.279.0> exit with reason normal in context child_terminated
2018-03-22 15:20:16.161 [error] <0.369.0> 'Elixir.BattleshipServer.Store' <0.369.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-9yJ7VlUqqfbehB2qgHOYVQ">>}}
2018-03-22 15:22:16.107 [error] <0.376.0> gen_server <0.376.0> terminated with reason: {socket_error,timeout}
2018-03-22 15:22:16.107 [error] <0.376.0> CRASH REPORT Process <0.376.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 15:22:16.107 [error] <0.372.0> gen_server <0.372.0> terminated with reason: {socket_error,timeout}
2018-03-22 15:22:16.107 [error] <0.372.0> CRASH REPORT Process <0.372.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 15:22:16.107 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13259>, <0.372.0>, <0.374.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64287 -> 127.0.0.1:5672">>) at <0.376.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 15:22:16.107 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13259>, <0.372.0>, <0.374.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64287 -> 127.0.0.1:5672">>) at <0.376.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 15:22:16.108 [error] <0.370.0> Supervisor {<0.370.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.371.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.372.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 15:22:16.108 [error] <0.370.0> Supervisor {<0.370.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.371.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.372.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 15:23:40.296 [error] <0.196.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.201.0> exit with reason normal in context child_terminated
2018-03-22 15:23:41.118 [error] <0.291.0> 'Elixir.BattleshipServer.Store' <0.291.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-2RKldIMPc5Mxnyg-OlBJXA">>}}
2018-03-22 15:25:42.756 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-22 15:25:43.435 [error] <0.286.0> 'Elixir.BattleshipServer.Store' <0.286.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-J27TF4CDHJ9WFxmrY_m3wA">>}}
2018-03-22 15:25:49.506 [error] <0.286.0>@Elixir.BattleshipServer.Store:wait_for_messages:33 gen_server <0.286.0> terminated with reason: no match of right hand value <<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423067}">> in 'Elixir.BattleshipServer.Store':wait_for_messages/1 line 33
2018-03-22 15:25:49.506 [error] <0.286.0>@Elixir.BattleshipServer.Store:wait_for_messages:33 CRASH REPORT Process <0.286.0> with 0 neighbours crashed with reason: no match of right hand value <<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423067}">> in 'Elixir.BattleshipServer.Store':wait_for_messages/1 line 33
2018-03-22 15:25:49.506 [error] <0.282.0>@Elixir.BattleshipServer.Store:wait_for_messages:33 Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at <0.286.0> exit with reason no match of right hand value <<"{\"player_2\":\"Alex\",\"player_1\":\"Manos\",\"game_id\":-576460752303423067}">> in 'Elixir.BattleshipServer.Store':wait_for_messages/1 line 33 in context child_terminated
2018-03-22 15:25:49.514 [error] <0.326.0> 'Elixir.BattleshipServer.Store' <0.326.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-nImyb0Lgb2e-fOzOYr-7lQ">>}}
2018-03-22 15:26:25.982 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-22 15:26:26.656 [error] <0.286.0> 'Elixir.BattleshipServer.Store' <0.286.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-xwjPJd6FSZYQ4jdHeItQJQ">>}}
2018-03-22 15:27:15.442 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-22 15:27:16.118 [error] <0.286.0> 'Elixir.BattleshipServer.Store' <0.286.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-el31TZgXmPJl2Cu83K7L_Q">>}}
2018-03-22 15:29:16.037 [error] <0.293.0> gen_server <0.293.0> terminated with reason: {socket_error,timeout}
2018-03-22 15:29:16.037 [error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 15:29:16.079 [error] <0.289.0> gen_server <0.289.0> terminated with reason: {socket_error,timeout}
2018-03-22 15:29:16.079 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7523>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64430 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 15:29:16.079 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 15:29:16.079 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7523>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:64430 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 15:29:16.079 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 15:29:16.079 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 16:01:00.336 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2018-03-22 16:01:00.964 [error] <0.296.0> CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.308.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.296.0>},60000]}} in gen_server:call/3 line 214
2018-03-22 16:01:00.964 [error] <0.292.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.308.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.296.0>},60000]}} in context start_error
2018-03-22 16:01:00.964 [error] <0.278.0> Supervisor 'Elixir.BattleshipServer.Supervisor' had child 'Elixir.Server.Supervisor' started with 'Elixir.Server.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.BattleshipServer.Store',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.308.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.296.0>},60000]}}}} in context start_error
2018-03-22 16:01:00.965 [error] <0.276.0> CRASH REPORT Process <0.276.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Server.Supervisor',{shutdown,{failed_to_start_child,'Elixir.BattleshipServer.Store',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.308.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.296.0>},60000]}}}}}},{'Elixir.BattleshipServer.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-03-22 16:03:06.149 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-22 16:03:06.749 [error] <0.286.0> CRASH REPORT Process <0.286.0> with 0 neighbours exited with reason: {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.298.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.286.0>},60000]}} in gen_server:call/3 line 214
2018-03-22 16:03:06.749 [error] <0.282.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.BattleshipServer.Store' started with 'Elixir.BattleshipServer.Store':start_link([]) at undefined exit with reason {{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.298.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.286.0>},60000]}} in context start_error
2018-03-22 16:03:06.750 [error] <0.268.0> Supervisor 'Elixir.BattleshipServer.Supervisor' had child 'Elixir.Server.Supervisor' started with 'Elixir.Server.Supervisor':start_link([]) at undefined exit with reason {shutdown,{failed_to_start_child,'Elixir.BattleshipServer.Store',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.298.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.286.0>},60000]}}}} in context start_error
2018-03-22 16:03:06.750 [error] <0.266.0> CRASH REPORT Process <0.266.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,'Elixir.Server.Supervisor',{shutdown,{failed_to_start_child,'Elixir.BattleshipServer.Store',{{shutdown,{server_initiated_close,406,<<"PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'game' in vhost '/': received 'topic' but current is 'fanout'">>}},{gen_server,call,[<0.298.0>,{call,{'exchange.declare',0,<<"game">>,<<"topic">>,false,false,false,false,false,[]},none,<0.286.0>},60000]}}}}}},{'Elixir.BattleshipServer.Application',start,[normal,[]]}} in application_master:init/4 line 134
2018-03-22 16:06:48.302 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2018-03-22 16:06:49.074 [error] <0.296.0> 'Elixir.BattleshipServer.Store' <0.296.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-vD4R-EmtGXwKvQor5byA0Q">>}}
2018-03-22 16:08:24.044 [error] <0.201.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.206.0> exit with reason normal in context child_terminated
2018-03-22 16:08:24.813 [error] <0.296.0> 'Elixir.BattleshipServer.Store' <0.296.0> received unexpected message in handle_info/2: {basic_consume_ok,#{consumer_tag => <<"amq.ctag-cEnRT1j6s256A3yJcvVxQw">>}}
