2018-03-22 18:14:03.937 [error] <0.274.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.279.0> exit with reason normal in context child_terminated
2018-03-22 18:16:04.660 [error] <0.376.0> gen_server <0.376.0> terminated with reason: {socket_error,timeout}
2018-03-22 18:16:04.661 [error] <0.372.0> gen_server <0.372.0> terminated with reason: {socket_error,timeout}
2018-03-22 18:16:04.661 [error] <0.376.0> CRASH REPORT Process <0.376.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 18:16:04.661 [error] <0.372.0> CRASH REPORT Process <0.372.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-22 18:16:04.661 [error] <0.370.0> Supervisor {<0.370.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.371.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.372.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 18:16:04.661 [error] <0.370.0> Supervisor {<0.370.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.371.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.372.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-22 18:16:04.661 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13231>, <0.372.0>, <0.374.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60141 -> 127.0.0.1:5672">>) at <0.376.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-22 18:16:04.661 [error] <0.371.0> Supervisor {<0.371.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.13231>, <0.372.0>, <0.374.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:60141 -> 127.0.0.1:5672">>) at <0.376.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:01:02.025 [error] <0.202.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.207.0> exit with reason normal in context child_terminated
2018-03-23 10:02:43.223 [error] <0.296.0> gen_server game_server terminated with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer :game_server but no handle_cast/2 clause was provided">>} in 'Elixir.Game.Server':handle_cast/2 line 630
2018-03-23 10:02:43.223 [error] <0.296.0> CRASH REPORT Process game_server with 0 neighbours crashed with reason: #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer :game_server but no handle_cast/2 clause was provided">>} in 'Elixir.Game.Server':handle_cast/2 line 630
2018-03-23 10:02:43.223 [error] <0.293.0> Supervisor 'Elixir.Server.Supervisor' had child 'Elixir.Game.Server' started with 'Elixir.Game.Server':start_link([]) at <0.296.0> exit with reason #{'__exception__' => true,'__struct__' => 'Elixir.RuntimeError',message => <<"attempted to cast GenServer :game_server but no handle_cast/2 clause was provided">>} in 'Elixir.Game.Server':handle_cast/2 line 630 in context child_terminated
2018-03-23 10:03:02.867 [error] <0.304.0> gen_server <0.304.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:03:02.867 [error] <0.304.0> CRASH REPORT Process <0.304.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:03:02.867 [error] <0.299.0> Supervisor {<0.299.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7743>, <0.300.0>, <0.302.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57458 -> 127.0.0.1:5672">>) at <0.304.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:03:02.867 [error] <0.299.0> Supervisor {<0.299.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7743>, <0.300.0>, <0.302.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57458 -> 127.0.0.1:5672">>) at <0.304.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:03:02.882 [error] <0.300.0> gen_server <0.300.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:03:02.882 [error] <0.300.0> CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:03:02.882 [error] <0.298.0> Supervisor {<0.298.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.299.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.300.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:03:02.882 [error] <0.298.0> Supervisor {<0.298.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.299.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.300.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:07:18.581 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:09:19.051 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:11:19.710 [error] <0.293.0> gen_server <0.293.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:11:19.725 [error] <0.289.0> gen_server <0.289.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:11:19.725 [error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:11:19.725 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:11:19.725 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:11:19.725 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7468>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57562 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:11:19.725 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:11:19.725 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7468>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57562 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:11:34.247 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:13:22.418 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:14:20.421 [error] <0.191.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.196.0> exit with reason normal in context child_terminated
2018-03-23 10:16:21.062 [error] <0.293.0> gen_server <0.293.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:16:21.062 [error] <0.293.0> CRASH REPORT Process <0.293.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:16:21.071 [error] <0.289.0> gen_server <0.289.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:16:21.071 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:16:21.071 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7444>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57730 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:16:21.071 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:16:21.071 [error] <0.288.0> Supervisor {<0.288.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7444>, <0.289.0>, <0.291.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57730 -> 127.0.0.1:5672">>) at <0.293.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:16:21.071 [error] <0.287.0> Supervisor {<0.287.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.288.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.289.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:16:21.093 [error] <0.307.0> gen_server <0.307.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:16:21.093 [error] <0.303.0> gen_server <0.303.0> terminated with reason: {socket_error,timeout}
2018-03-23 10:16:21.094 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:16:21.094 [error] <0.303.0> CRASH REPORT Process <0.303.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-03-23 10:16:21.094 [error] <0.302.0> Supervisor {<0.302.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7600>, <0.303.0>, <0.305.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57731 -> 127.0.0.1:5672">>) at <0.307.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:16:21.094 [error] <0.302.0> Supervisor {<0.302.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.7600>, <0.303.0>, <0.305.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:57731 -> 127.0.0.1:5672">>) at <0.307.0> exit with reason reached_max_restart_intensity in context shutdown
2018-03-23 10:16:21.094 [error] <0.301.0> Supervisor {<0.301.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.302.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.303.0> exit with reason {socket_error,timeout} in context child_terminated
2018-03-23 10:16:21.094 [error] <0.301.0> Supervisor {<0.301.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.302.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.303.0> exit with reason reached_max_restart_intensity in context shutdown
